// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0--rc1
// source: audiodialog.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAudioDialogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAudioDialogRequest) Reset() {
	*x = CreateAudioDialogRequest{}
	mi := &file_audiodialog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAudioDialogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAudioDialogRequest) ProtoMessage() {}

func (x *CreateAudioDialogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_audiodialog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAudioDialogRequest.ProtoReflect.Descriptor instead.
func (*CreateAudioDialogRequest) Descriptor() ([]byte, []int) {
	return file_audiodialog_proto_rawDescGZIP(), []int{0}
}

type CreateAudioDialogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DialogId      string                 `protobuf:"bytes,1,opt,name=dialog_id,json=dialogId,proto3" json:"dialog_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    string                 `protobuf:"bytes,3,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAudioDialogResponse) Reset() {
	*x = CreateAudioDialogResponse{}
	mi := &file_audiodialog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAudioDialogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAudioDialogResponse) ProtoMessage() {}

func (x *CreateAudioDialogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_audiodialog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAudioDialogResponse.ProtoReflect.Descriptor instead.
func (*CreateAudioDialogResponse) Descriptor() ([]byte, []int) {
	return file_audiodialog_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAudioDialogResponse) GetDialogId() string {
	if x != nil {
		return x.DialogId
	}
	return ""
}

func (x *CreateAudioDialogResponse) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *CreateAudioDialogResponse) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

var File_audiodialog_proto protoreflect.FileDescriptor

const file_audiodialog_proto_rawDesc = "" +
	"\n" +
	"\x11audiodialog.proto\x12\vaudiodialog\"\x1a\n" +
	"\x18CreateAudioDialogRequest\"v\n" +
	"\x19CreateAudioDialogResponse\x12\x1b\n" +
	"\tdialog_id\x18\x01 \x01(\tR\bdialogId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x03 \x01(\tR\n" +
	"receiverId2z\n" +
	"\x12AudioDialogService\x12d\n" +
	"\x11CreateAudioDialog\x12%.audiodialog.CreateAudioDialogRequest\x1a&.audiodialog.CreateAudioDialogResponse\"\x00B\x03Z\x01.b\x06proto3"

var (
	file_audiodialog_proto_rawDescOnce sync.Once
	file_audiodialog_proto_rawDescData []byte
)

func file_audiodialog_proto_rawDescGZIP() []byte {
	file_audiodialog_proto_rawDescOnce.Do(func() {
		file_audiodialog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audiodialog_proto_rawDesc), len(file_audiodialog_proto_rawDesc)))
	})
	return file_audiodialog_proto_rawDescData
}

var file_audiodialog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_audiodialog_proto_goTypes = []any{
	(*CreateAudioDialogRequest)(nil),  // 0: audiodialog.CreateAudioDialogRequest
	(*CreateAudioDialogResponse)(nil), // 1: audiodialog.CreateAudioDialogResponse
}
var file_audiodialog_proto_depIdxs = []int32{
	0, // 0: audiodialog.AudioDialogService.CreateAudioDialog:input_type -> audiodialog.CreateAudioDialogRequest
	1, // 1: audiodialog.AudioDialogService.CreateAudioDialog:output_type -> audiodialog.CreateAudioDialogResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_audiodialog_proto_init() }
func file_audiodialog_proto_init() {
	if File_audiodialog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audiodialog_proto_rawDesc), len(file_audiodialog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audiodialog_proto_goTypes,
		DependencyIndexes: file_audiodialog_proto_depIdxs,
		MessageInfos:      file_audiodialog_proto_msgTypes,
	}.Build()
	File_audiodialog_proto = out.File
	file_audiodialog_proto_goTypes = nil
	file_audiodialog_proto_depIdxs = nil
}
