// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0--rc1
// source: audiodialog.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AudioDialogService_CreateAudioDialog_FullMethodName = "/audiodialog.AudioDialogService/CreateAudioDialog"
	AudioDialogService_DeleteAudioDialog_FullMethodName = "/audiodialog.AudioDialogService/DeleteAudioDialog"
)

// AudioDialogServiceClient is the client API for AudioDialogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioDialogServiceClient interface {
	CreateAudioDialog(ctx context.Context, in *CreateAudioDialogRequest, opts ...grpc.CallOption) (*CreateAudioDialogResponse, error)
	DeleteAudioDialog(ctx context.Context, in *DeleteAudioDialogRequest, opts ...grpc.CallOption) (*DeleteAudioDialogResponse, error)
}

type audioDialogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioDialogServiceClient(cc grpc.ClientConnInterface) AudioDialogServiceClient {
	return &audioDialogServiceClient{cc}
}

func (c *audioDialogServiceClient) CreateAudioDialog(ctx context.Context, in *CreateAudioDialogRequest, opts ...grpc.CallOption) (*CreateAudioDialogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAudioDialogResponse)
	err := c.cc.Invoke(ctx, AudioDialogService_CreateAudioDialog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioDialogServiceClient) DeleteAudioDialog(ctx context.Context, in *DeleteAudioDialogRequest, opts ...grpc.CallOption) (*DeleteAudioDialogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAudioDialogResponse)
	err := c.cc.Invoke(ctx, AudioDialogService_DeleteAudioDialog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AudioDialogServiceServer is the server API for AudioDialogService service.
// All implementations must embed UnimplementedAudioDialogServiceServer
// for forward compatibility.
type AudioDialogServiceServer interface {
	CreateAudioDialog(context.Context, *CreateAudioDialogRequest) (*CreateAudioDialogResponse, error)
	DeleteAudioDialog(context.Context, *DeleteAudioDialogRequest) (*DeleteAudioDialogResponse, error)
	mustEmbedUnimplementedAudioDialogServiceServer()
}

// UnimplementedAudioDialogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioDialogServiceServer struct{}

func (UnimplementedAudioDialogServiceServer) CreateAudioDialog(context.Context, *CreateAudioDialogRequest) (*CreateAudioDialogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAudioDialog not implemented")
}
func (UnimplementedAudioDialogServiceServer) DeleteAudioDialog(context.Context, *DeleteAudioDialogRequest) (*DeleteAudioDialogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAudioDialog not implemented")
}
func (UnimplementedAudioDialogServiceServer) mustEmbedUnimplementedAudioDialogServiceServer() {}
func (UnimplementedAudioDialogServiceServer) testEmbeddedByValue()                            {}

// UnsafeAudioDialogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioDialogServiceServer will
// result in compilation errors.
type UnsafeAudioDialogServiceServer interface {
	mustEmbedUnimplementedAudioDialogServiceServer()
}

func RegisterAudioDialogServiceServer(s grpc.ServiceRegistrar, srv AudioDialogServiceServer) {
	// If the following call panics, it indicates UnimplementedAudioDialogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AudioDialogService_ServiceDesc, srv)
}

func _AudioDialogService_CreateAudioDialog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAudioDialogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioDialogServiceServer).CreateAudioDialog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioDialogService_CreateAudioDialog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioDialogServiceServer).CreateAudioDialog(ctx, req.(*CreateAudioDialogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AudioDialogService_DeleteAudioDialog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAudioDialogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AudioDialogServiceServer).DeleteAudioDialog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AudioDialogService_DeleteAudioDialog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AudioDialogServiceServer).DeleteAudioDialog(ctx, req.(*DeleteAudioDialogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AudioDialogService_ServiceDesc is the grpc.ServiceDesc for AudioDialogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioDialogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audiodialog.AudioDialogService",
	HandlerType: (*AudioDialogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAudioDialog",
			Handler:    _AudioDialogService_CreateAudioDialog_Handler,
		},
		{
			MethodName: "DeleteAudioDialog",
			Handler:    _AudioDialogService_DeleteAudioDialog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "audiodialog.proto",
}
